runtime: python37

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: 100ms
  max_concurrent_requests: 50

resources:
  memory_gb: 1.0
